dist: xenial
language: python

python:
  - '3.7'

install:
  - python -m pip install pipenv
  - pipenv install --dev
  - python setup.py sdist bdist_wheel

script: "twine upload --skip-existing -u $username -p $password dist/*"
