dist: xenial
language: python

python:
  - '3.7'
  - '3.6'

install:
  - python -m pip install pipenv
  - pipenv install --dev

script: 
  - pipenv run flake8 .
  - python setup.py sdist bdist_wheel

deploy:
  provider: pypi
  username: $username
  password: $password
  on:
    branch: master
