dist: xenial
language: python

python:
  - '3.7'
  - '3.6'

install:
  - python -m pip install pipenv
  - pipenv install --dev

script: 
  - pipenv run flake8 .
  - pipenv run python setup.py sdist bdist_wheel

after_success:
  - pipenv run twine upload --skip-existing --user $username --password $password dist/*
  on:
    branch: master