site_name: Jaspion Docs
site_description: The docs of Jaspion project
site_url: https://jaspion.readthedocs.io/
repo_url: https://github.com/Otoru/jaspion/
site_author: Vitor Hugo de Oliveira Vargas
nav:
    - 'Home': index.md
    - 'Get Started': get-started.md
    - 'How to Install': install.md
    - 'Tools': tools.md
    - 'Examples': examples.md
theme: readthedocs
