site_name: Jaspion Docs
nav:
    - Index: index.md
    - Get Started: get_started.md
    - Installation Instructions: installation_instructions.md
    - Tools:
        - Haskey: tools.md#haskey
        - Filtrate: tools.md#filtrate
        - AbstractBaseHandler: tools.md#abstractbasehandler
    - examples: examples.md
theme: readthedocs
