site_name: Jaspion Docs
site_description: The docs of Jaspion project
site_url: https://jaspion.readthedocs.io/
repo_url: https://github.com/Otoru/jaspion/
site_author: Vitor Hugo de Oliveira Vargas
nav:
    - home: home.md
    - Tools: tools.md
    - examples: examples.md
theme: 
    name: mkdocs
    highlightjs: true
