site_name: Jaspion
nav:
    - Index: index.md
    - Get Started: get_started.md
    - Installation Instructions: installation_instructions.md
    - Tools: tools.md
    - Examples: examples.md
theme: readthedocs
