site_name: Jaspion Docs
site_description: The docs of Jaspion project
site_url: https://jaspion.readthedocs.io/
repo_url: https://github.com/Otoru/jaspion/
site_author: Vitor Hugo de Oliveira Vargas
nav:
    - Index: index.md
    - Get Started: get_started.md
    - Installation Instructions: installation_instructions.md
    - Tools:
        - Haskey: tools.md#haskey
        - Filtrate: tools.md#filtrate
        - AbstractBaseHandler: tools.md#abstractbasehandler
    - examples: examples.md
theme: readthedocs
